# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]; then
	PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=
stty -ixon
shopt -s autocd
eval "$(zoxide init bash)"
eval "$(dircolors)"

[[ -f ~/.config/bash/env ]] && . ~/.config/bash/env

[ -f ~/.config/bash/aliases ] && . ~/.config/bash/aliases

# fzf key bindings
[[ -f /usr/share/fzf/shell/key-bindings.bash ]] && . /usr/share/fzf/shell/key-bindings.bash

# User specific aliases and functions
if [ -d ~/.config/bash/bashrc.d ]; then
	for rc in ~/.config/bash/bashrc.d/*; do
		if [ -f "$rc" ]; then
			. "$rc"
		fi
	done
fi
unset rc

eval "$(starship init bash)"
export STARSHIP_CONFIG=~/.config/startship/starship.toml
