"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
$username\
${custom.sc}\
$directory\
$git_branch\
$nodejs\
$python\
$docker_context$fill\
$git_status\
$line_break$character
"""
right_format = """
"""

palette = 'catppuccin_mocha'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[os]
style = "fg:maroon"
disabled = false

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "fg:maroon"
style_root = "fg:maroon"
format = '[ $user ]($style)'

[directory]
style = "fg:blue"
format = "[$path ]($style)"
truncation_length = 5
truncation_symbol = ""

[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = ""
"Music" = "󰝚"
"Pictures" = ""
"Developer" = "󰲋"

".dotfiles" = ""

[git_branch]
symbol = ""
style = "bold fg:green"
format = '[$symbol $branch(:$remote_branch)]($style)'

[git_status]
style = "fg:peach"
# format = '[[($all_status$ahead_behind )](fg:color_aqua)]($style)'
untracked = '[${count}](fg:blue)'
ahead = '[${count}󱦲](fg:blue)'
behind = '[${count}󱦳](fg:orange)'
diverged = '[${ahead_count}󱦲](fg:color_blue)[${behind_count}󱦳](fg:orange)'
up_to_date = '[](fg:green)'
staged = '[${count}](fg:color_fg0)'
modified = '[${count}󱇨](fg:yellow)'
deleted = '[${count}](fg:red)'
format = '([\($all_status$ahead_behind\)]($style))'
[nodejs]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_blue)]($style)'

[python]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version )(\($virtualenv\)) ](fg:color_blue)]($style)'

[docker_context]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol( $context) ](fg:color_bg1)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[󰁕](bold fg:rosewater)'
error_symbol = '[󰁕](bold fg:red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'

[time]
disabled = false

[fill]
symbol = ' '

[custom.sc]
command = "wc ~/.bash_history | awk '{print $1}'" # shows output of command
when = true
style = "fg:teal bold"
format = '[$output]($style) '
