"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
$username\
$directory\
$git_branch\
$nodejs\
$python\
$docker_context$fill\
$git_status\
$line_break$character
"""
right_format = """
"""

palette = 'catppuccin_macchiato'

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

[os]
style = "fg:maroon"
disabled = false

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "fg:maroon"
style_root = "fg:maroon"
format = '[ $user ]($style)'

[directory]
style = "fg:green"
format = "[$path ]($style)"
truncation_length = 5
truncation_symbol = ""

[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = ""
"Music" = "󰝚"
"Pictures" = ""
"Developer" = "󰲋"

".dotfiles" = ""

[git_branch]
symbol = ""
style = "bold fg:color_aqua"
format = '[$symbol $branch(:$remote_branch)]($style)'

[git_status]
style = "fg:color_yellow"
# format = '[[($all_status$ahead_behind )](fg:color_aqua)]($style)'
untracked = '${count}'
ahead = '[${count}󱦲](fg:color_blue)'
behind = '[${count}󱦳](fg:color_orange)'
diverged = '[${ahead_count}󱦲](fg:color_blue)[${behind_count}󱦳](fg:color_orange)'
up_to_date = '[](fg:color_green)'
staged = '[${count}](fg:color_fg0)'
modified = '[${count}󱇨](fg:color_yellow)'
deleted = '[${count}](fg:color_red)'
format = '([\($all_status$ahead_behind\)]($style))'
[nodejs]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_blue)]($style)'

[python]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version )(\($virtualenv\)) ](fg:color_blue)]($style)'

[docker_context]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol( $context) ](fg:color_bg1)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[󰁕](bold fg:color_green)'
error_symbol = '[󰁕](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'

[time]
disabled = false

[fill]
symbol = ' '
